In [18]:
import numpy as np
from math import sqrt

In [195]:
def is_definite_positive(M):
  if np.array_equal(A, A.T):
        try:
          if cholesky_decomposition(M) is not None:
            return True
          else:
            return False
        except:
            return False
  else:
        return False
  # return np.all(np.linalg.eigvals(x) > 0)
  # try :
  #   
  # except:
  #   return False

In [78]:
def get_matrix():
  r = int(input("Enter the number of rows and columns: "))
  rowList = []
  for i in range(r):
    row = list(map(float, input().split(" ")))
    rowList.append(row)
  return np.matrix(rowList)

In [200]:
def get_vector():
  v = list(map(float, input("Enter vector: ").split(" ")))
  return np.array(v)

In [184]:
def matrix_multiply(A,B):
  r1 = len(A)
  c1 = len(A[0])

  r2 = len(B)
  c2 = len(B[0])

  if c1 != r2:
    print('Number of A columns must equal number of B rows.')
    sys.exit()

  C = np.zeros((rowsA, colsB))

  for i in range(rowsA):
    for j in range(colsB):
      total = 0
      for ii in range(colsA):
        total += A[i][ii] * B[ii][j]
      C[i][j] = total

  return C

In [139]:
def gauss_lu(M):
  n = len(M)
  a = np.copy(M)
  L = np.zeros_like(M)
  U = np.zeros_like(M)

  for i in range(0, n):
    L[i, i] = 1


  for k in range(0,n-1):
    for i in range(k+1,n):
      if a[i,k] != 0.0:
        lam = a[i,k]/a[k,k]
        a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
        a[i,k] = lam
        
  for i in range(0, n):
    for j in range(0, n):
      if j >= i:
        U[i, j] = a[i, j]
      else:
        L[i, j] = a[i, j]
    
  return L, U

In [80]:
def cholesky_decomposition(M):
    A = np.copy(M)
    n = A.shape[0]
    R = np.zeros_like(A)

    for k in range(n):
        R[k, k] = sqrt(A[k, k])
        R[k, k + 1:] = A[k, k + 1:] / float(R[k, k])
        for j in range(k + 1, n):
            A[j, j:] = A[j, j:] - R[k, j] * R[k, j:]

    return R

In [201]:
def solve_system(A, b):
  
  n = len(A)
  if A[n-1, 0] == 0:
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
      tmp = b[i]
      for j in range(i+1, n):
        tmp -= A[i,j] * x[j]
      x[i] = tmp / A[i,i]
    return x
  else:
    x = np.zeros_like(b)
    AM = np.copy(A)
    BM = np.copy(b)
 
    indices = list(range(n))
    for fd in range(n): 
      fdScaler = 1.0 / AM[fd, fd]
      for j in range(n): 
        AM[fd, j] *= fdScaler
      BM[fd] *= fdScaler
     
      for i in indices[0:fd] + indices[fd+1:]: 
        crScaler = AM[i, fd]
        for j in range(n): 
          AM[i, j] = AM[i, j] - crScaler * AM[fd, j]
        BM[i] = BM[i] - crScaler * BM[fd]

    return BM

In [204]:
m = get_matrix()
v = get_vector()

if len(m) == len(v):
  if is_definite_positive(m):
    R = cholesky_decomposition(m)
    RT = R.T
    print(R)
    print(R.T)
    y = solve_system(R, v)
    x = solve_system(RT, y)
    print(x)
  else:
    L, U = gauss_lu(m)
    y = solve_system(L, v)
    x = solve_system(U, y)
    print(x)
else:
  print("Invalid input")


Enter the number of rows and columns: 2
2 1
1 2
Enter vector: 2 33
[-9.66666667 21.33333333]


# **Sample example for LU solving**
   Enter the number of rows and columns: 3
 1 1 1
 4 3 -1
 3 5 3

 Enter vector:1 6 4


```
L =  [
  [ 1.  0.  0.]
  [ 4.  1.  0.]
  [ 3. -2.  1.]
  ]
```
```
 U = [
   [  1.   1.   1.]
  [  0.  -1.  -5.]
  [  0.   0. -10.]
 ]
```

` x = [ 1.   0.5 -0.5]`