In [1]:
import numpy as np
from math import sqrt

In [30]:
def is_definite_positive(M):
  return np.all(np.linalg.eigvals(M) > 0)

In [11]:
def check_symmetric(a, rtol=1e-05, atol=1e-08):
  return np.allclose(a, a.T, rtol=rtol, atol=atol)

In [3]:
def get_matrix():
  r = int(input("Enter the number of rows and columns: "))
  rowList = []
  for i in range(r):
    row = list(map(float, input().split(" ")))
    rowList.append(row)
  return np.matrix(rowList)

In [4]:
def matrix_multiply(A,B):
  r1 = len(A)
  c1 = len(A[0])

  r2 = len(B)
  c2 = len(B[0])

  if c1 != r2:
    print('Number of A columns must equal number of B rows.')
    sys.exit()

  C = np.zeros((rowsA, colsB))

  for i in range(rowsA):
    for j in range(colsB):
      total = 0
      for ii in range(colsA):
        total += A[i][ii] * B[ii][j]
      C[i][j] = total

  return C

In [5]:
def gauss_lu(M):
  n = len(M)
  a = np.copy(M)
  L = np.zeros_like(M)
  U = np.zeros_like(M)

  for i in range(0, n):
    L[i, i] = 1


  for k in range(0,n-1):
    for i in range(k+1,n):
      if a[i,k] != 0.0:
        lam = a[i,k]/a[k,k]
        a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
        a[i,k] = lam
        
  for i in range(0, n):
    for j in range(0, n):
      if j >= i:
        U[i, j] = a[i, j]
      else:
        L[i, j] = a[i, j]
    
  return L, U

In [34]:
def LDLT_decomposition(A):
  if check_symmetric(m):
    if is_definite_positive(m):
      L, U = gauss_lu(m)
      LT = L.T
      LT_reverse = np.linalg.inv(LT)
      D = np.dot(U, LT_reverse)
      return L,D
    else:
      print("Invalid Input Matrix A is not positive definite")
  else:
    print("Invalid Input Matrix A is notsymmetric")

In [38]:
# m = np.matrix([
#                [2, 4, -2, 2],
#                [4, 9, -1, 6],
#                [-2, -1, 14, 13],
#                [2, 6, 13, 35]
# ])

m = get_matrix()

L,D = LDLT_decomposition(m)
print("L = ")
print(L)
print("D = ")
print(D)


L = 
[[ 1  0  0  0]
 [ 2  1  0  0]
 [-1  3  1  0]
 [ 1  2  3  1]]
D = 
[[2. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 2.]]


# **Sample example for LU solving**
   Enter the number of rows and columns: 4


``` 
2 4 -2 2
4 9 -1 6
-2 -1 14 13
2 6 13 35
```


L
```
1 0 0 0
2 1 0 0
-1 3 1 0
1 2 3 1
```

D
```
2 0 0 0
0 1 0 0
0 0 3 0
0 0 0 2
```

L^T
```
1 2 -1 1
0 1 3 2
0 0 1 3
0 0 0 1
```
